### ISSUE TITLE
Issues to compile

### ISSUE THREAD

**Issue by almendieta** [Bizarrus/NSISMySQL#1]
Hi, thanks for your library, it's REALLY an awesome complement to NSIS. Once said that, explain my problem (I'm a complete newbie in C++). After install the last Windows SDK, I tried to compile the code, but got the next answer:

external unresolved popstring symbol referenced in function "wchar_t * __cdecl getString(int)" (?getString@@YAPEA_WH@Z)

Unresolved myatoi external symbol referenced in SetCredentials function

external symbol g_stringsize unresolved

external symbol g_stacktop unresolved

external symbol g_variables unresolved

I had to move the file pluginapi.lib to NSIS folder in order compiler see the file.

It would great if you include DLLs so anyone like me, trying only get them to deal with my own NSIS script, can go on quickly to the finish line :) Please get this remark as a suggestion only, and thank you in advance for your answer.

**Comment by Bizarrus** [comment]
Hey, compiled `DLL` files already online (see the releases Page!): https://github.com/Bizarrus/NSISMySQL/releases

![image](https://user-images.githubusercontent.com/1371300/77305426-485c8900-6cf6-11ea-891d-77b7c192c76b.png)

**Comment by almendieta** [comment]
Thank you for your answer! I'm just finished to test them in my NSIS script, but got a problem: just receive message boxes including parameters like server, database, user and password I've just  place in the script. Checking the source code could see that messageboxes but anything more, like functions to connect to MySQL host. Not sure where I can find database functions stuff to look at how functions library. In the other hand, is there a way to receive any response from the remote database to interact with it? For instance, if I send the query "SELECT ID FROM CLIENTS WHERE ID='1569'", how can I do to receive the database response? Thanks a LOT for your help!

**Comment by almendieta** [comment]
This library do NOTHING but throw messages! It´s absolutely USELESS, a waste of time!!
